//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lagerverwaltung
{
    using System;
    using System.Collections.Generic;
    
    public partial class bestand
    {
        public int PaletteID { get; set; }
        public int LagerID { get; set; }
        public string Bezeichnung { get; set; }
        public int Einheiten { get; set; }
    
        public virtual lager lager { get; set; }
    }
}
